### ISSUE TITLE
[Bug] Website downgrade?

### ISSUE THREAD

**Issue by pidgeon777** [codicocodes/dotfyle#121]
Some days ago I was able to search for specific plugins such as `LazyVim/LazyVim`. Now this plugin is missing.

Also this URL worked, now not anymore:

https://dotfyle.com/neovim/configurations/top?page=1&plugins=LazyVim%2FLazyVim%2CL3MON4D3%2FLuaSnip

Moreover, it is not possible to register or sign in to the website? These links are greyed out when trying to click on them:

![image](https://github.com/codicocodes/dotfyle/assets/13739892/f791ab92-1f80-4ae0-b76c-824311a1d579)

Finally, after the plugin search it was possible to obtain links pointing to the line of code where the searched plugins were defined, and it was a very cool feature. Now also this feature is missing.

So, I don't know if this is a bug, but it seems a big website downgrade to me compared to the previous version?

**Comment by mimikun** [comment]
Me too. I'm having trouble because I can't generate a README.

**Comment by codicocodes** [comment]
Thanks for reporting. It took some time for me to notice because I was busy at work today. It looks like last night my hosting provider erroneously deployed a very old version of my code. A 7 month old commit leading to this error.

I have not interacted with the code for the past 3 weeks since Ive been on vacation.

However I've now reverted to the correct deployment and have reported the issue to my Provider.

Honestly to me it's baffling that a cloud provider can have this happen, still waiting to hear from them.
