### ISSUE TITLE
Question on updating plugin

### ISSUE THREAD

**Issue by MisanthropicBit** [codicocodes/dotfyle#129]
I submitted a plugin a while ago in #48 and since I've now released version 1.0.0, I'd like to add the announcement to twin. I'm not really sure how to do this after looking over the repo but I imagine I need to create an account or readd the plugin via the form link in the README?

However, I don't want to make certain private profile information public or stored on a server somewhere, and github [is pretty vague on what this information entails](https://docs.github.com/en/apps/oauth-apps/using-oauth-apps/authorizing-oauth-apps#types-of-requested-data). I've read the terms of service and privacy policy.

* Can you tell me exactly what data is read/stored, for what purpose, and if any data is made public?
* Alternatively, is there a way to submit updates to a plugin without creating an account?
* Can I still submit plugins via the `SUBMITTED-PLUGINS.md` file?

**Comment by codicocodes** [comment]
I currently do not store email addresses. I store the GitHub username, the GitHub user ID, the avatar url and a read only GitHub access token. You can see the details here: https://github.com/codicocodes/dotfyle/blob/1dc4d46b1cf55483a24a64d98114e8a0ab91e38e/prisma/schema.prisma#L13-L29

This is the scopes requested on the token: https://github.com/codicocodes/dotfyle/blob/1dc4d46b1cf55483a24a64d98114e8a0ab91e38e/src/lib/server/auth/github/settings.ts#L7 

I believe `scope=read:user` is readonly public profile & repo information but it was a really long time since I worked on that part.

The GitHub user id is used to authenticate you as a user.

The information is made public on a page like this, https://dotfyle.com/codicocodes , together with plugins you've authored and configurations you've synced.

The form is not able to be used to add updates/announcement about plugins though, so it's not really relevant for this. The form is only usable to add new plugins.

For updates, usually the best way is to write in my discord server. You can make an issue here as well.

Either way you're not guaranteed that I notice the update but hopefully I do and remember it when i'm writing the next issue.

**Comment by codicocodes** [comment]
I don't scrape `SUBMITTED-PLUGINS.md` any longer since adding the form

**Comment by MisanthropicBit** [comment]
Thank you for the very detailed reply 🙂 that's all very reassuring. If it makes sense, perhaps it might be nice to add this to the docs/readme? Or at least, there's this issue to refer to.

> For updates, usually the best way is to write in my discord server. You can make an issue here as well.

Thanks. I've made an issue here on the update: #131 since I don't have a discord account.

> I don't scrape SUBMITTED-PLUGINS.md any longer since adding the form

Good to know, and thanks again for your continuing efforts on the site 🥳 feel free to close.
