### ISSUE TITLE
plugin scan detect all the plugins and detect commented ones 

### ISSUE THREAD

**Issue by grzebiel** [codicocodes/dotfyle#17]
It looks like plugin scan doesn't detect all the plugins, and detect ones that are commented out Take a look at mine [repo](https://github.com/grzebiel/dotfiles/blob/701a5f1c5a68f779731fad84c1e96928af235202/.config/nvim/lua/plugins.lua) you can see the plugin list there that are not detected:
```lua
[...]
  -- status line
  use 'itchyny/lightline.vim'
  -- use {"rebelot/heirline.nvim",
  --   config = function() require 'configs/heirline' end}

  -- ack/ag support
  use 'mileszs/ack.vim'

  use 'octol/vim-cpp-enhanced-highlight'
  use 'nickhutchinson/vim-cmake-syntax'
  use 'potatoesmaster/i3-vim-syntax'
[...]
```
![image](https://user-images.githubusercontent.com/10223474/231760877-44440e1e-014b-4a16-a562-f73f2c8c943e.png)

Also worth noting, that it detects [rebelot/heirline.nvim](https://dotfyle.com/plugins/rebelot/heirline.nvim) as installed, but in fact it is commented out.

**Comment by codicocodes** [comment]
I am not planning on addressing either of these issues at the moment, they are inherent to how the parser works, and I don't find it to be important to focus on 100% accuracy.

The way the parser works is that I index [rockerboo/awesome-neovim](https://github.com/rockerBOO/awesome-neovim) for popular plugins, then I check the config files for mentions of those plugins.

Only plugins mentioned in awesome-neovim will be identified, I hope to increase this in the future by adding more plugin sources, but it will likely never identify all plugins with 100% accuracy because I'm not planning on spinning up a full neovim instance and run an install.

Regarding commented out plugins, I'm not interested in processing an AST to identify if the plugin is commented out or not and handle it differently. I don't think it's worth the effort for now and want to focus on more valuable features. It would also increase the complexity of the code and slow down the parser.

If you care about the correctness, I suggest removing commented out plugins from your config, and once the sync supports removing plugins they will be removed from your dotfyle page.
