### ISSUE TITLE
Moved plugin is not properly updated

### ISSUE THREAD

**Issue by willothy** [codicocodes/dotfyle#50]
[nvim-cokeline](https://github.com/willothy/nvim-cokeline) was moved to my account recently, but only the old owner's [repo](https://dotfyle.com/plugins/noib3/cokeline.nvim) shows up on dotfyle and configs containing it aren't being tracked even though readme changes / updates are.

**Comment by codicocodes** [comment]
Please update it upstream at https://github.com/rockerBOO/awesome-neovim or add it to https://github.com/codicocodes/dotfyle/blob/main/SUBMITTED-PLUGINS.md, but fixing it in rockerBOO is probably best.

The reason readme changes and such are tracked are likely because GitHub will redirect for some time, before it starts 404ing.

**Comment by willothy** [comment]
Gotcha! Thanks. Wasn't aware dotfyle fetched from awesome-neovim, that's pretty cool. Great work with this, love the site :)

**Comment by codicocodes** [comment]
No problem, and great to hear that you like it :D 

I'm doing a push adding some plugins rn not currently tracked in awesome-neovim, so will add cokeline as well!

But you should still push it to awesome-neovim for sure!
